### ISSUE TITLE
Odom is published twice

### ISSUE THREAD

**Issue by UAVlover** [NOKOV-MOCAP/mocap_nokov#1]
when the data was updated, the odometer was published twice，which is meanless. 

    if (config.publishOdom)
    {
      odom.header.frame_id = config.parentFrameId;
      odom.child_frame_id = config.childFrameId;
      odomPublisher.publish(odom);
    }
    if (config.publishOdom) 
    {
      odom.header.frame_id = config.parentFrameId;
      odom.child_frame_id = config.childFrameId;
      odomPublisher.publish(odom);
    }

**Comment by duguguang** [comment]
the duplicated code has been removed , thank you!
